steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA',
           '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-latest',
           '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run',
           'deploy', '$_SERVICE_NAME',
           '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-latest',
           '--region', '$_REGION',
           '--platform', '$_PLATFORM',
           '--quiet']

substitutions:
  _SERVICE_NAME: spinbot
  _REGION: us-central1
  _PLATFORM: managed

images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
  - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-latest
