steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t', '$_DOCKER_REGISTRY/$REPO_NAME:$SHORT_SHA',
           '-t', '$_DOCKER_REGISTRY/$REPO_NAME:$BRANCH_NAME-latest',
           '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           '$_DOCKER_REGISTRY/$REPO_NAME:$BRANCH_NAME-latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run',
           'deploy', '$_SERVICE_NAME',
           '--image', '$_DOCKER_REGISTRY/$REPO_NAME:$BRANCH_NAME-latest',
           '--region', '$_REGION',
           '--platform', '$_PLATFORM',
           '--quiet']

substitutions:
  _SERVICE_NAME: spinbot
  _REGION: us-central1
  _PLATFORM: managed
  _DOCKER_REGISTRY: us-docker.pkg.dev/spinnaker-community/spinbot

images:
  - $_DOCKER_REGISTRY/$REPO_NAME:$SHORT_SHA
  - $_DOCKER_REGISTRY/$REPO_NAME:$BRANCH_NAME-latest
