github:
  token: "secret:spinnaker-community/spinbot-gh-token#latest"

logging:
  level: INFO

storage:
  gcs:
    bucket: spinbot-cache
    project: spinnaker-community
    path: cache

policy:
  repos:
    - spinnaker/spinnaker
    - spinnaker/spinnaker.io
    - spinnaker/deck-kayenta
    - spinnaker/kayenta
    - spinnaker/keel
  policies:
    - name: stale_issue_policy

event:
  repos:
    - spinnaker/buildtool
    - spinnaker/clouddriver
    - spinnaker/deck
    - spinnaker/deck-kayenta
    - spinnaker/echo
    - spinnaker/fiat
    - spinnaker/front50
    - spinnaker/gate
    - spinnaker/igor
    - spinnaker/kayenta
    - spinnaker/keel
    - spinnaker/kork
    - spinnaker/orca
    - spinnaker/rosco
    - spinnaker/halyard
    - spinnaker/spin
    - spinnaker/spinnaker
    - spinnaker/spinnaker.io
  handlers:
    - name: label_issue_comment_event_handler
    - name: issue_comment_assign_handler
    - name: log_event_handler
      config:
        payload: false
    - name: pull_request_message_handler
    - name: filetype_check_pull_request_handler
      config:
        omit_repos:
          - spinnaker/spinnaker
          - spinnaker/spinnaker.io
          - spinnaker/deck
          - spinnaker/spin
    - name: release_branch_pull_request_handler
      config:
        omit_repos:
          - spinnaker/spinnaker
          - spinnaker/spinnaker.io
    - name: master_branch_pull_request_handler
      config:
        omit_repos:
          - spinnaker/spinnaker
          - spinnaker/spinnaker.io
    - name: pull_request_closed_event_handler
